/*
 * codeslide.net
 *
 * @license
 * Forked from mydraft.cc by Sebastian Stehle
 * Copyright (c) Do Duc Quan. All rights reserved.
*/

export const texts = {
    common: {
        about: 'About',
        alignHorizontalCenter: 'Horizontal Center',
        alignHorizontalLeft: 'Horizontal Left',
        alignHorizontalRight: 'Horizontal Right',
        alignment: 'Alignment',
        alignVerticalBottom: 'Vertical Bottom',
        alignVerticalCenter: 'Vertical Center',
        alignVerticalTop: 'Vertical Top',
        apply: 'Apply',
        animation: 'Animation',
        aspectRatio: 'Preserve aspect ratio',
        background: 'Background Color',
        bringForwards: 'Bring Forwards',
        bringToFront: 'Bring to Front',
        copy: 'Copy',
        copyTooltip: 'Copy Items',
        custom: 'Custom',
        cut: 'Cut',
        cutTooltip: 'Cut Items',
        delete: 'Delete',
        deleteDiagramConfirm: 'Do you really want to delete the presentation?',
        diagram: 'Canvas',
        distributeHorizontally: 'Distribute Horizontally',
        distributeVertically: 'Distribute Vertically',
        documentation: 'Documentation',
        duplicate: 'Duplicate',
        error: 'Output',
        findIcon: 'Find Icon',
        findPage: 'Find Page',
        findShape: 'Find Shape',
        fontSize: 'Font Size',
        foregroundColor: 'Foreground Color',
        group: 'Group',
        groupTooltip: 'Group Items',
        height: 'Height',
        help: 'Help',
        id: 'ID',
        icons: 'Icons',
        imageChangeURL: 'Change Image by URL',
        layout: 'Layout',
        link: 'Link',
        load: 'Load',
        loadingDiagram: 'Loading presentation...',
        loadingDiagramDone: 'Loading presentation completed successfully.',
        loadingDiagramFailed: 'Loading presentation failed with internal error.',
        lock: 'Lock',
        lockTooltip: 'Lock or unlock item',
        masterPage: 'Master Page',
        more: 'More',
        newDiagram: 'New',
        newDiagramTooltip: 'New Presentation',
        newVersion: 'A new version is available. Please press F5 to reload them.',
        none: 'None',
        noRecentDocument: 'No recent document found',
        outline: 'Outline',
        openFromFile: 'Open',
        openFromFileTooltip: 'Open presentation from file',
        optionsTooltip: 'Show more options (CTRL + O)',
        ordering: 'Ordering',
        page: 'Page',
        pages: 'Pages',
        palette: 'Palette',
        paste: 'Paste',
        pasteTooltip: 'Paste Items',
        prefix: 'code-slide',
        presentation: 'Presentation',
        printDiagrams: 'Print Presentation',
        printingStarted: 'Printing started...',
        properties: 'Properties',
        recent: 'Recent',
        redo: 'Redo',
        remove: 'Delete',
        rename: 'Rename',
        renameTooltip: 'Rename presentation',
        removeTooltip: 'Delete selected items',
        saveDiagram: 'Download',
        saveDiagramToFileTooltip: 'Export to PDF',
        saveDiagramTooltip: 'Download',
        savingDiagram: 'Saving presentation...',
        savingDiagramDone: 'Saving presentation completed successfully.',
        savingDiagramFailed: 'Saving presentation failed with internal error.',
        sendBackwards: 'Send Backwards',
        sendToBack: 'Send to Back',
        settings: 'Settings',
        shapes: 'Shapes',
        shapeChangeSvg: 'Change Shape by SVG',
        strokeColor: 'Stroke Color',
        strokeThickness: 'Stroke Thickness',
        tableDelimiterCol: ',',
        tableDelimiterRow: ';',
        textAlignment: 'Text Alignment',
        transform: 'Transform',
        undo: 'Undo',
        ungroup: 'Ungroup',
        ungroupTooltip: 'Ungroup Items',
        unsaved: 'unsaved',
        visual: 'Visual',
        walkthrough: 'Walkthrough',
        width: 'Width',
        zoomIn: 'Zoom In',
        zoomOut: 'Zoom Out',
    }
};
