name: PR

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm i

      - name: Run Tests 
        run: npm run test:coverage
        
      - name: Run Build 
        run: npm run build
