name: Build & Test

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm i

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Tests 
        run: npm run test:ci

      - name: Fix coverage paths
        run: npm run fix-coverage-paths

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: code-slide/ui

      - name: Run Build 
        run: npm run build